-- MySQL Script generated by MySQL Workbench
-- Wed Oct 28 16:47:53 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema earglass
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema earglass
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `earglass` DEFAULT CHARACTER SET utf8 ;
USE `earglass` ;

-- -----------------------------------------------------
-- Table `earglass`.`USERTYPE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `earglass`.`USERTYPE` (
  `Type_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Type_name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `earglass`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `earglass`.`USER` (
  `idUSER` INT NOT NULL AUTO_INCREMENT,
  `Id` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Gender` VARCHAR(1) NOT NULL,
  `Address` VARCHAR(100) NOT NULL,
  `Birth` VARCHAR(8) NOT NULL,
  `Phonenumber` VARCHAR(13) NOT NULL,
  `USERTYPE_Type_name` VARCHAR(45) NOT NULL,
  `user_score` FLOAT NULL DEFAULT 0,
  PRIMARY KEY (`idUSER`),
  UNIQUE KEY (`Id` ASC),
  UNIQUE KEY (`idUSER` ASC),
  UNIQUE KEY (`Phonenumber` ASC),
  INDEX `fk_USER_USERTYPE1_idx` (`USERTYPE_Type_name` ASC),
  CONSTRAINT `fk_USER_USERTYPE1`
    FOREIGN KEY (`USERTYPE_Type_name`)
    REFERENCES `earglass`.`USERTYPE` (`Type_name`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `earglass`.`TASK`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `earglass`.`TASK` (
  `Name` VARCHAR(45) NOT NULL,
  `Description` TEXT(1000) NOT NULL,
  `Min_period` INT NOT NULL DEFAULT 0,
  `Status` VARCHAR(45) NOT NULL DEFAULT 'ongoing',
  `FK_idManager` INT NOT NULL,
  PRIMARY KEY (`Name`),
  INDEX `fk_TASK_USER1_idx` (`FK_idManager` ASC),
  CONSTRAINT `fk_TASK_USER1`
    FOREIGN KEY (`FK_idManager`)
    REFERENCES `earglass`.`USER` (`idUSER`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `earglass`.`ORIGIN_DATA_TYPE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `earglass`.`ORIGIN_DATA_TYPE` (
  `idORIGIN_DATA_TYPE` INT NOT NULL AUTO_INCREMENT,
  `Schema_info` VARCHAR(1000) NOT NULL,
  `Mapping_info` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`idORIGIN_DATA_TYPE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `earglass`.`MAPPING_TASK_TYPE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `earglass`.`MAPPING_TASK_TYPE` (
  `FK_TASK_Name` VARCHAR(45) NOT NULL,
  `FK_idORIGIN_DATA_TYPE` INT NOT NULL,
  PRIMARY KEY (`FK_TASK_Name`, `FK_idORIGIN_DATA_TYPE`),
  INDEX `fk_TASK_has_ORIGIN_DATA_TYPE_ORIGIN_DATA_TYPE1_idx` (`FK_idORIGIN_DATA_TYPE` ASC),
  INDEX `fk_TASK_has_ORIGIN_DATA_TYPE_TASK1_idx` (`FK_TASK_Name` ASC),
  CONSTRAINT `fk_TASK_has_ORIGIN_DATA_TYPE_TASK1`
    FOREIGN KEY (`FK_TASK_Name`)
    REFERENCES `earglass`.`TASK` (`Name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_TASK_has_ORIGIN_DATA_TYPE_ORIGIN_DATA_TYPE1`
    FOREIGN KEY (`FK_idORIGIN_DATA_TYPE`)
    REFERENCES `earglass`.`ORIGIN_DATA_TYPE` (`idORIGIN_DATA_TYPE`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `earglass`.`ORIGIN_DSF`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `earglass`.`ORIGIN_DSF` (
  `idORIGIN_DSF` INT NOT NULL AUTO_INCREMENT,
  `Origin_file` VARCHAR(200) NOT NULL,
  `Summit_num` INT NOT NULL DEFAULT 0,
  `Date` DATETIME NOT NULL,
  `FK_TASK_Name` VARCHAR(45) NOT NULL,
  `FK_idORIGIN_DATA_TYPE` INT NOT NULL,
  `FK_idUSER` INT NULL,
  PRIMARY KEY (`idORIGIN_DSF`),
  UNIQUE KEY (`idORIGIN_DSF` ASC),
  INDEX `fk_ORIGIN_DSF_MAPPING_TASK_TYPE1_idx` (`FK_TASK_Name` ASC, `FK_idORIGIN_DATA_TYPE` ASC),
  INDEX `fk_ORIGIN_DSF_USER1_idx` (`FK_idUSER` ASC),
  CONSTRAINT `fk_ORIGIN_DSF_MAPPING_TASK_TYPE1`
    FOREIGN KEY (`FK_TASK_Name` , `FK_idORIGIN_DATA_TYPE`)
    REFERENCES `earglass`.`MAPPING_TASK_TYPE` (`FK_TASK_Name` , `FK_idORIGIN_DATA_TYPE`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ORIGIN_DSF_USER1`
    FOREIGN KEY (`FK_idUSER`)
    REFERENCES `earglass`.`USER` (`idUSER`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `earglass`.`PARSING_DSF`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `earglass`.`PARSING_DSF` (
  `idPARSING_DSF` INT NOT NULL AUTO_INCREMENT,
  `Parsing_file` VARCHAR(200) NOT NULL,
  `Submit_num` INT NOT NULL DEFAULT 0,
  `Num_row` INT NOT NULL DEFAULT 0,
  `Duplicate_row` INT NOT NULL DEFAULT 0,
  `Null_subtitles` FLOAT NOT NULL DEFAULT 0,
  `Null_starttime` FLOAT NOT NULL DEFAULT 0,
  `Null_endtime` FLOAT NOT NULL DEFAULT 0,
  `Null_duration` FLOAT NOT NULL DEFAULT 0,
  `Num_longvalue` INT NOT NULL DEFAULT 0,
  `Num_Lduration` INT NOT NULL DEFAULT 0,
  `Num_Sduration` INT NOT NULL DEFAULT 0,
  `FK_idORIGIN_DSF` INT NOT NULL DEFAULT 0,
  `System_score` INT NOT NULL DEFAULT 0,
  `Pass` BINARY(1) NULL,
  `Average_score` FLOAT NULL,
  `Total_status` VARCHAR(45) NULL,
  `FK_idUSER` INT NOT NULL,
  PRIMARY KEY (`idPARSING_DSF`),
  UNIQUE KEY (`idPARSING_DSF` ASC),
  UNIQUE KEY (`FK_idORIGIN_DSF` ASC),
  INDEX `fk_PARSING_DSF_ORIGIN_DSF1_idx` (`FK_idORIGIN_DSF` ASC),
  CONSTRAINT `fk_PARSING_DSF_ORIGIN_DSF1`
    FOREIGN KEY (`FK_idORIGIN_DSF`)
    REFERENCES `earglass`.`ORIGIN_DSF` (`idORIGIN_DSF`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `earglass`.`TASK_DATA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `earglass`.`TASK_DATA` (
  `idTASK_DATA` INT NOT NULL AUTO_INCREMENT,
  `FK_TASK_Name` VARCHAR(45) NULL,
  `Start` VARCHAR(11) NOT NULL,
  `End` VARCHAR(11) NOT NULL,
  `Caption` VARCHAR(1000) NOT NULL,
  `Part_num` INT NOT NULL DEFAULT 1,
  `FK_idPARSING_DSF` INT NULL,
  `FK_idUSER` INT NULL,
  PRIMARY KEY (`idTASK_DATA`, `FK_idPARSING_DSF`),
  INDEX `fk_TASK_DATA_TASK1_idx` (`FK_TASK_Name` ASC),
  INDEX `fk_TASK_DATA_PARSING_DSF1_idx` (`FK_idPARSING_DSF` ASC),
  CONSTRAINT `fk_TASK_DATA_TASK1`
    FOREIGN KEY (`FK_TASK_Name`)
    REFERENCES `earglass`.`TASK` (`Name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_TASK_DATA_PARSING_DSF1`
    FOREIGN KEY (`FK_idPARSING_DSF`)
    REFERENCES `earglass`.`PARSING_DSF` (`idPARSING_DSF`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `earglass`.`EVALUATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `earglass`.`EVALUATION` (
  `idEVALUATION` INT NOT NULL,
  `FK_idPARSING_DSF` INT NOT NULL,
  `FK_idUSER` INT NULL,
  `Score` INT NULL,
  `Pass` VARCHAR(45) NULL,
  `Start_time` VARCHAR(11) NOT NULL,
  `End_time` VARCHAR(11) NOT NULL,
  `Deadline` DATETIME NOT NULL,
  `Status` VARCHAR(45) NOT NULL DEFAULT 'ongoing',
  PRIMARY KEY (`idEVALUATION`),
  INDEX `idEVALUATION_EVALUATION1_idx` (`idEVALUATION` ASC),
  CONSTRAINT `fk_PARSING_DSF_has_USER_PARSING_DSF1`
    FOREIGN KEY (`FK_idPARSING_DSF`)
    REFERENCES `earglass`.`PARSING_DSF` (`idPARSING_DSF`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_PARSING_DSF_has_USER_USER1`
    FOREIGN KEY (`FK_idUSER`)
    REFERENCES `earglass`.`USER` (`idUSER`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;